//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.OperacionesReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesReference1.IOperaciones")]
    public interface IOperaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Saludar", ReplyAction="http://tempuri.org/IOperaciones/SaludarResponse")]
        string Saludar(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Saludar", ReplyAction="http://tempuri.org/IOperaciones/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        int Suma(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        int Resta(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones/MultiplicacionResponse")]
        int Multiplicacion(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones/MultiplicacionResponse")]
        System.Threading.Tasks.Task<int> MultiplicacionAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Division", ReplyAction="http://tempuri.org/IOperaciones/DivisionResponse")]
        int Division(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Division", ReplyAction="http://tempuri.org/IOperaciones/DivisionResponse")]
        System.Threading.Tasks.Task<int> DivisionAsync(int Numero1, int Numero2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesChannel : PL.OperacionesReference1.IOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesClient : System.ServiceModel.ClientBase<PL.OperacionesReference1.IOperaciones>, PL.OperacionesReference1.IOperaciones {
        
        public OperacionesClient() {
        }
        
        public OperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludar(string Nombre) {
            return base.Channel.Saludar(Nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string Nombre) {
            return base.Channel.SaludarAsync(Nombre);
        }
        
        public int Suma(int Numero1, int Numero2) {
            return base.Channel.Suma(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2) {
            return base.Channel.SumaAsync(Numero1, Numero2);
        }
        
        public int Resta(int Numero1, int Numero2) {
            return base.Channel.Resta(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2) {
            return base.Channel.RestaAsync(Numero1, Numero2);
        }
        
        public int Multiplicacion(int Numero1, int Numero2) {
            return base.Channel.Multiplicacion(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicacionAsync(int Numero1, int Numero2) {
            return base.Channel.MultiplicacionAsync(Numero1, Numero2);
        }
        
        public int Division(int Numero1, int Numero2) {
            return base.Channel.Division(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int Numero1, int Numero2) {
            return base.Channel.DivisionAsync(Numero1, Numero2);
        }
    }
}
